# Generated by Django 3.2.17 on 2023-02-03 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='major',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctors.major'),
        ),
    ]
