# Generated by Django 3.2.16 on 2023-01-29 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_auto_20230129_1830'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='medical_center',
            new_name='center',
        ),
    ]
