# Generated by Django 3.2.16 on 2023-01-29 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0003_rename_medical_center_doctor_center'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='major',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctors.major'),
        ),
    ]
